### PR TITLE
Kernel upgrade

### PR DESCRIPTION
**Pull request by jacobweinstock**
## Description

Upgrades kernel to 5.15

## Why is this needed

Fixes: #

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by chrisdoherty4** [comment]
Is this ready to be reviewed?

**Comment by jacobweinstock** [comment]
> @jacobweinstock Is this ready to be reviewed?

Not quite. I have a few things left to work out around the release process and migrating kernel settings from 5.10.

**Comment by nmaiti** [comment]
@jacobweinstock are you working on this pr? Need the upgrade of kernel.

**Comment by jacobweinstock** [comment]
> @jacobweinstock are you working on this pr? Need the upgrade of kernel.

Hey @nmaiti. Yes, still working on this.

**Comment by jacobweinstock** [comment]
Hey @Ram-srini. Apologies, i dont know what a "BKM" is.

**Comment by terry-hasegawa** [comment]
Hi @jacobweinstock,
When will you merge this pull request?
On Dell XR5610 (which is newest server) the hook is stuck.
We are hoping this pull will be merged.

**Comment by jacobweinstock** [comment]
The kernel upgrade is handled in #205

**Pull request closed without merging**
