### PR TITLE
Fixes DHCP and removes BPFilter

### PR DESCRIPTION
**Pull request by thebsdbox**
## Description

Fixes DHCP in hook.yaml
Removes BPFilter in kernel

## Why is this needed
Improves reliability and reduces time to boot.

Fixes: #

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Review by markyjackson-taulia — APPROVED** [review]

**Comment by thebsdbox** [comment]
Fixes #43

**Comment by detiber** [comment]
I was hoping to download the artifact from the CI job, but it looks like it failed to upload (without a failure sadly), testing locally it looks like the working directory is dirty after building the image, causing the image name to also have `dirty` in it. Might need to add `/dist` to `.gitignore` to prevent that.

**Comment by displague** [comment]
I see other configs are enabled as modules, is the initrd for this kernel produced as well? 
Any reason to enable the bpf module (modularly)?

**Comment by thebsdbox** [comment]
Yeah, it's a good point. I only removed the bpfilter include as it was a blocking init process by the kernel and adds a few seconds before init starts. I don't know how deep we want to go diverging from the default config upstream to having our own truly optimised kernel. 

We could perhaps make significant savings in memory usage from the initramdisk if we go into "deep" into the hornets nest of kconfig.

**Pull request merged**
