### PR TITLE
Adds 5.10.57 Kernel

### PR DESCRIPTION
**Pull request by thebsdbox**
## Description

This adds a new updates LTS Kernel

## Why is this needed

The older kernel was a little long in the tooth. 

Fixes: #

## How are existing users impacted? What migration steps/scripts do we need?

No impact.

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Review by nshalman — APPROVED** [review]
Looks good to me. DCO check is unhappy and it looks like there are merge conflicts. Happy to re-approve once that's all cleaned up. Thanks!

**Comment by detiber** [comment]
lgtm, should there also be an updated config for aarch64, though?

**Comment by thebsdbox** [comment]
Yeah, I was hoping to do the rest today but it's been a crazy day. I'll try and get it sorted tomorrow.

**Comment by thebsdbox** [comment]
Fixed aarch64 and hook_debug.yaml 

`make dist` completes successfully and images exist on quay.io !

**Pull request merged**
