### PR TITLE
Update hook kernel to 5.10.85

### LINKED ISSUE #90: Intel I225-LM not detected (old kernel issue most likely)
## Expected Behaviour
Hook detects and loads the `igc` module on systems with Intel I225-LM NICs present.

## Current Behaviour
Hook boots but seemingly fails to detect Intel I225-LM devices and the `igc` module does not get loaded. This results in no network connectivity if a system is connected to the provisioning network via an interface with this chipset.

## Possible Solution
Update the kernel. Hook uses 5.10.57 which is many releases behind upstream 5.10 LTS (currently at 5.10.78) and likely the cause here. Ideally, hook should move to using mainline releases for better compatibility with new hardware as it makes it into new kernel releases.

## Steps to Reproduce (for bugs)
1. Obtain a system with an Intel I225 interface. We tested the [Minisforum HX90](https://store.minisforum.com/pages/product). Configure it so PXE is enabled.
2. Establish tinkerbell services and connect device with I225 adapter to network with access to services
3. Create a hardware profile and workflow for the device
4. Power on device
5. System will chainload iPXE from PXE and hook will load via iPXE
6. Hook will begin to boot but eventually stall out due to having no network connectivity due to not having loaded a module to enable the I225 NIC.

## Context
We are intending to use tinkerbell to deploy many client devices that unfortunately only have a single I225-LM NIC on them. We can sidestep this issue by not using hook and doing automated OS installs however that is going to be a slower option than using hook to deploy disk images. Ideally, hook should function on modern hardware.

To be sure, both Fedora 34 and Debian 11 were also tested on the system with an I225-LM NIC and both were able to detect the NIC and loaded the `igc` module. Whatever the issue is that affects hook supporting this devices seems to have been fixed in later LTS kernels and mainline.

## Questions
Is there a specific reason hook has been held back to such a dated LTS kernel release? This definitely is going to hamper support of new hardware.

I noticed some [patches](https://github.com/tinkerbell/hook/tree/main/kernel/bcc.patches) so I could see those requiring some work to validate against or port to a newer kernel. I could see time being a constraint here. Maintaining a kernel build is certainly not a zero time commitment.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS): Fedora Silverblue and CoreOS

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details: podman containers

cc: @jkl92 @storrgie

### PR DESCRIPTION
**Pull request by jmpolom**
## Description

This PR updates the hook kernel to 5.10.85 and could maybe close #90. Earlier 5.10.x kernel versions, such as 5.10.57 which was the previously released kernel for hook, seemed to have a bug in the `igc` module that prevented certain NICs from functioning. Later kernel versions fixed this issue.

We need to discuss longer term plans for supporting hook though. Hook had not seen a kernel update for many months, but meanwhile new hardware requiring support continues to come onto the market. We should formulate a plan for moving hook to the next LTS kernel which is 5.15 and also a release cadence as new kernels release upstream.

## Why is this needed

Fixes: #90

## How Has This Been Tested?

**Note:** this still needs to be run through the standard tinkerbell CI tests.

This has been tested with a single device ([Minisforum HX90](https://store.minisforum.com/products/hx90?variant=40508846440609)) as detailed in the initial issue. More thorough testing with a larger variety of hardware devices might be desirable.

After making the detailed changes, Hook and the kernel were built outside of CI on my development desktop. A test instance of the tinkerbell sandbox was setup using [ansible and podman](https://github.com/epiphyte-org/sandbox/tree/ansible-podman_container) on the same workstation. After the example sandbox workflow was modified slightly to account for the presence of an nvme SSD in the HX90, the device was powered on and successfully imaged via hook and the example sandbox workflow. This resulted in the HX90 having a bootable Ubuntu Focal image installed.

## How are existing users impacted? What migration steps/scripts do we need?

Users should only need to download and deploy the updated pre-built binaries for hook if they desire to upgrade. This upgrade is really not "mandatory" as prior versions of hook should continue to function _just fine_. Many users may opt to not upgrade unless they are encountering compatibility issues with the prior release of hook. The remaining work that needs to happen is on the project side to get these changes built and published for public consumption.

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Review by markyjackson-taulia — CHANGES_REQUESTED** [review]
Thank you for this pr. Kindly sign the DCO

**Comment by jmpolom** [comment]
Looks like the kernel build passes but hook can't be built with linuxkit because it can't locate the necessary kernel container image. Is there an alternate registry that should be specified in `hook.yaml` to test the built kernel in the build? Seems like the kernel container gets committed somewhere during the CI job but isn't pulled into the hook build.

I will also go back and do the DCO.

**Review by thebsdbox — DISMISSED** [review]
/lgtm

**Comment by thebsdbox** [comment]
Once dco is sorted this should be good to go.

**Comment by jmpolom** [comment]
@thebsdbox DCO is complete. Commits are signed however github does not seem to recognize my gpg key for some reason that I will have to sort out later.

**Review by markyjackson-taulia — APPROVED** [review]

**Comment by jmpolom** [comment]
Is this good to merge now?

**Comment by jmpolom** [comment]
@thebsdbox and @markyjackson-taulia can this get merged?

**Comment by markyjackson-taulia** [comment]
We will need to debug the failure. I am tied up for the rest of today but if no one looks by tomorrow morning, I will get it some eyes.

**Comment by jmpolom** [comment]
Seems to [fail](https://github.com/tinkerbell/hook/runs/4791403874?check_suite_focus=true#step:10:1299) when it can't find the hook-kernel image with `5.10.85` tag on quay, because it doesn't exist there. I'm not sure how to make this pass since I can't push an image to quay. I'm not sure how you guys are doing that.

**Comment by thebsdbox** [comment]
@Mergifyio refresh

**Comment by thebsdbox** [comment]
Holy moly I can merge this!

**Pull request merged**
