### PR TITLE
enable MD and build in some network drivers

### PR DESCRIPTION
**Pull request by swills**
## Description

I needed this for my setup, I think others might find them useful. I
wanted to setup md raid, so needed the md stuff built in. And in order
to netboot from certain hardware, the driver for the hardware has to be
built in, so add that as well.

## Why is this needed

Enables using MD, fixes netboot on certain hardware

Fixes: #

## How Has This Been Tested?
Yep, tested it on my hardware

## How are existing users impacted? What migration steps/scripts do we need?

Shouldn't cause any issues

## Checklist:

I have:

- [N/A] updated the documentation and/or roadmap (if required)
- [N/A] added unit or e2e tests
- [N/A] provided instructions on how to upgrade

### CODE REVIEW

**Comment by thebsdbox** [comment]
Awesome!

Thanks for this change.

**Comment by swills** [comment]
Ping?

**Comment by jmpolom** [comment]
What is the status of this? This is a great complement to #90 and I believe hook should move forward with building more hardware support directly into the kernel instead of relying on modules in the initramfs. Concerns may be that this increases the size of the kernel image however this should be balanced by a reduction in initramfs size.

How can we move this forward?

cc: @tstromberg @thebsdbox @storrgie @jkl92

**Review by thebsdbox — APPROVED** [review]

**Comment by thebsdbox** [comment]
Yeah I'm happy with that summary.

**Comment by swills** [comment]
NIC drivers in unit range don't help when kernel command line includes ip=dhcp.

**Comment by jacobweinstock** [comment]
hmmm.....Hey @thebsdbox, looks like the CI could use some help here if you have any cycles?

**Review by thebsdbox — DISMISSED** [review]

**Comment by thebsdbox** [comment]
Something to do with mergify is blocking this.. 🙄

**Review by markyjackson-taulia — APPROVED** [review]

**Comment by thebsdbox** [comment]
@Mergifyio refresh

**Comment by jacobweinstock** [comment]
@Mergifyio refresh

**Review by jacobweinstock — APPROVED** [review]

**Pull request merged**
