### PR TITLE
Fix documentation

### PR DESCRIPTION
**Pull request by ghoneycutt**
## Description

Going through install process and fixing docs as I go

## Why is this needed

Because the documentation does not work

### CODE REVIEW

**Comment by ghoneycutt** [comment]
This is a work in progress

**Comment by markyjackson-taulia** [comment]
Can you move it to draft pr status? Also, thank you so much for this! This is what I love about community

**Comment by ghoneycutt** [comment]
Well.. it can be merged as is. Was waiting to see if there are more changes.

**Comment by thebsdbox** [comment]
Dont we publish hook to an s3 bucket? we still want to give people the option of having something pre-built.

**Comment by gianarb** [comment]
The CI/CD system that does that is a pile of sadness and it doesn't to work
since we moved the repo from my account to here

David made an s3 bucket available for us and I think it will get fixed when
this work will be over with multi arch support
https://github.com/tinkerbell/hook/pull/37

**Comment by ghoneycutt** [comment]
This is ready for merge

**Review by detiber — APPROVED** [review]

**Review by markyjackson-taulia — APPROVED** [review]

**Pull request merged**
