### PR TITLE
Enable CONFIG_SCSI_MPT3SAS for x86_64

### PR DESCRIPTION
**Pull request by ader1990**
Storage devices that need CONFIG_SCSI_MPT3SAS to be enabled are fairly common on baremetals and I would like to add support for such devices.

### CODE REVIEW

**Comment by jacobweinstock** [comment]
Apologies, we re-open this PR. I'm trying to the validation check to run.

**Comment by chrisdoherty4** [comment]
@jacobweinstock I wonder if the repository configuration is borked because this is happening across multiple PRs?

**Comment by jacobweinstock** [comment]
oh, doh 🤦🏼 . this is this issue: https://github.com/tinkerbell/hook/issues/145.

**Comment by jacobweinstock** [comment]
Hey @ader1990, apologies for the very long delay here. We've recently updated the build process and added additional kernels. 6.6, for example. #226 gets your PR merged into main. Thanks!

**Pull request closed without merging**
